FROM ghcr.io/linuxserver/baseimage-alpine:3.15

ENV LANG=C.UTF-8 BGMI_PATH="/config/conf/bgmi"
ENV PUID=1000
ENV PGID=1000
## true 和 false
ENV TRANSMISSION=true
## true 和 false
ENV TRANSMISSION_WEB_CONTROL=true
## BGMI密码
ENV BGMI_ADMIN_TOKEN=password
## BGMI默认数据源
ENV BGMI_SOURCE=mikan_project

ADD ./data /home/bgmi-docker

RUN { \
	apk add --update linux-headers gcc python3-dev libffi-dev openssl-dev cargo libxslt-dev zlib-dev libxml2-dev musl-dev nginx bash supervisor transmission-daemon python3 cargo curl tzdata wget zip; \
	curl https://bootstrap.pypa.io/get-pip.py | python3; \
	pip install cryptography; \
	pip install 'transmissionrpc'; \
}

RUN mkdir -p /home/bgmi-docker && \
    cd /home/bgmi-docker && \
    wget https://github.com/BGmi/BGmi/archive/refs/heads/master.zip && \
    unzip /home/bgmi-docker/master.zip && \
    mv /home/bgmi-docker/BGmi-master /home/bgmi-docker/BGmi && \
    pip install /home/bgmi-docker/BGmi && \
    mkdir -p /home/bgmi-docker/transmission-web-control && \
    cd /home/bgmi-docker/transmission-web-control && \
    wget https://github.com/ronggang/transmission-web-control/raw/master/release/install-tr-control-cn.sh --no-check-certificate && \
    echo 1 | bash install-tr-control-cn.sh && \
    mkdir -p /video && \
    rm -rf /home/bgmi-docker/master.zip && \
    rm -rf /var/cache/apk/* && \
    rm -rf /root/.cache && \
    rm -rf /tmp/*

COPY ./root /

VOLUME ["/bgmi"]
VOLUME [ "/video" ]

EXPOSE 88 9091 51413/tcp 51413/udp
