version: '3.3'
services:
    bgmi:
        container_name: BGmi
        restart: always
        volumes:
            - './bgmi:/bgmi'
            - '/media:/media'
        ports:
            - '80:80'
            - '6888:6888/tcp'
            - '6888:6888/udp'
        environment:
            - TZ=Asia/Shanghai
            - PGID=1000
            - PUID=1000
            - UMASK=022
            - MEDIA_DIR=/media/cartoon
            - DOWNLOAD_DIR=/media/downloads
            - BGMI_DATA_SOURCE=mikan_project
            - BGMI_HTTP_ADMIN_TOKEN=password
            - BGMI_HARDLINK_USE=true
            - FILEBROWSER_USE=true
            - ARIA2_UPDATE_TRACKERS=true
            - ARIA2_CUSTOM_TRACKER_URL=https://raw.githubusercontent.com/DDS-Derek/Aria2-Pro-Docker/main/tracker/all.list
            - ARIA2_LISTEN_PORT=6888
            - ARIA2_RPC_PORT=6800
            - ARIA2_RPC_SECRET=
            - ARIA2_DISK_CACHE=
            - ARIA2_IPV6_MODE=
        cap_add:
            - NET_ADMIN
        image: 'ddsderek/bgmi-all-in-one:aria2'