FROM alpine:3.12

RUN { \
	apk add --update zip unzip git tini linux-headers gcc python3-dev libffi-dev openssl-dev cargo libxslt-dev zlib-dev libxml2-dev musl-dev nginx bash supervisor transmission-daemon python3 cargo curl tzdata shadow jq findutils; \
	curl https://bootstrap.pypa.io/get-pip.py | python3; \
	pip install cryptography; \
	pip install 'transmissionrpc'; \
}
