FROM codysk/bgmi-all-in-one:1.2.5

COPY ./bgmi_hardlink_helper /home/bgmi-docker/bgmi_hardlink_helper
ADD ./entrypoint.sh /home/bgmi-docker/entrypoint.sh
ADD ./conf/bgmi_nginx.conf /home/bgmi-docker/config/bgmi_nginx.conf
ADD ./conf/bgmi_supervisord.ini /home/bgmi-docker/config/bgmi_supervisord.ini
ADD ./test/bgmi_hardlink_helper.py /home/bgmi-docker/bgmi_hardlink_helper/bgmi_hardlink_helper.py

RUN mkdir -p /media && \
    chmod 755 /home/bgmi-docker/entrypoint.sh

VOLUME [ "/media" ]