#!/bin/bash
#     _         _       ____    ____
#    / \   _ __(_) __ _|___ \  |  _ \ _ __ ___
#   / _ \ | '__| |/ _` | __) | | |_) | '__/ _ \
#  / ___ \| |  | | (_| |/ __/  |  __/| | | (_) |
# /_/   \_\_|  |_|\__,_|_____| |_|   |_|  \___/
#
# https://github.com/P3TERX/Aria2-Pro-Docker https://github.com/DDS-Derek/Aria2-Pro-Docker
#
# Copyright (c) 2020-2022 P3TERX <https://p3terx.com> DDSRem DDSDerek <https://blog.ddsrem.gq>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.

. /home/tools/aria2/aria2_pro/etc/init-base

mkdir -p ${ARIA2_CONF_DIR} ${SCRIPT_DIR} ${DOWNLOAD_DIR}

PROFILES="
aria2.conf
script.conf
core
delete.sh
dht.dat
dht6.dat
LICENSE
"

DOWNLOAD_PROFILE

[[ ! -f "${ARIA2_CONF_DIR}/aria2.session" ]] && {
    rm -rf "${ARIA2_CONF_DIR}/aria2.session"
    touch "${ARIA2_CONF_DIR}/aria2.session"
}

if ! [[ "${UPDATE_TRACKERS}" = "false" || "${UPDATE_TRACKERS}" = "disable" ]]; then
    (crontab -l ; echo "0	7	*	*	*	su abc -c 'sleep $((RANDOM % 1800)); bash /config/aria2/script/tracker.sh /config/aria2/aria2.conf RPC 2>&1 | tee /config/logs/tracker.log'") | crontab -
    PROFILES="tracker.sh"
    DOWNLOAD_PROFILE
    bash ${SCRIPT_DIR}/tracker.sh ${ARIA2_CONF}
fi

exit 0
