#!/usr/bin/with-contenv bash

first_lock="/bgmi_install.lock"
bangumi_db="$BGMI_PATH/bangumi.db"
transmission_setting="/config/conf/transmission/settings.json"
bgmi_nginx_conf="/config/conf/nginx/bgmi.conf"
bgmi_hardlink_helper="/config/bgmi_hardlink_helper/bgmi_hardlink_helper.py"
bgmi_hardlink_helper_config="/config/bgmi_hardlink_helper/config.py"

if [ ! -f $first_lock ]; then
	init_proc
fi

chown -R abc:abc \
	/config
chown abc:abc \
   	/video \
   	/video/downloads \
   	/video/cartoon


function init_proc {
	touch $first_lock

	if [ ! -z $BGMI_ADMIN_TOKEN ]; then
		admin_token=$BGMI_ADMIN_TOKEN
	fi

	if [ ! -z $BGMI_SOURCE ]; then
		data_source=$BGMI_SOURCE
	fi

	if [ ! -f $bangumi_db ]; then
		bgmi install
		bgmi source $data_source
		bgmi config ADMIN_TOKEN $admin_token
		bgmi config SAVE_PATH /video/downloads
		bgmi config DOWNLOAD_DELEGATE transmission-rpc
	else
		bgmi upgrade
		bash /home/bgmi-docker/BGmi/bgmi/others/crontab.sh
	fi

	mkdir -p /var/run/nginx
	mkdir -p /config/conf/bgmi
	mkdir -p /config/conf/transmission
	mkdir -p /config/conf/nginx
	mkdir -p /config/bgmi_hardlink_helper
	mkdir -p /config/log
	mkdir -p /video/cartoon
	mkdir -p /video/downloads

    ## transmission
	if [[ ${TRANSMISSION} = 'false' ]]; then
		rm -rf /root/etc/services.d/transmission
	fi
	cp /home/bgmi-docker/config/transmission-daemon /etc/conf.d/transmission-daemon
	if [ ! -f $transmission_setting ]; then
		cp /home/bgmi-docker/config/transmission_settings.json $transmission_setting
	fi
	if [[ ${TRANSMISSION_WEB_CONTROL} = 'false' ]]; then
		cd /opt
		echo 3 | bash install-tr-control-cn.sh > /dev/null
   	fi

	## Nginx
	rm -rf /etc/nginx/conf.d
	ln -s /bgmi/conf/nginx /etc/nginx/conf.d
	if [ ! -f $bgmi_nginx_conf ]; then
		cp /home/bgmi-docker/config/bgmi_nginx.conf $bgmi_nginx_conf
	fi
	sed -i "s/user nginx/user abc/g" /etc/nginx/nginx.conf

    ## bgmi_hardlink_helper
	if [ ! -f $bgmi_hardlink_helper ]; then
		cp /home/bgmi-docker/bgmi_hardlink_helper/bgmi_hardlink_helper.py $bgmi_hardlink_helper
	fi
	if [ ! -f $bgmi_hardlink_helper_config ]; then
		cp /home/bgmi-docker/bgmi_hardlink_helper/config.py $bgmi_hardlink_helper_config
	fi
	cd /bgmi/bgmi_hardlink_helper
	python3 bgmi_hardlink_helper.py install_cron
}
