version: '3.3'
services:
    bgmi:
        container_name: BGmi
        restart: always
        volumes:
            - './bgmi:/bgmi'
            - '/media:/media'
        ports:
            - '80:80'
            - '51413:51413/tcp'
            - '51413:51413/udp'
        environment:
            - TZ=Asia/Shanghai
            - PGID=1000
            - PUID=1000
            - UMASK=022
            - MEDIA_DIR=/media/cartoon
            - DOWNLOAD_DIR=/media/downloads
            - BGMI_DATA_SOURCE=mikan_project
            - BGMI_HTTP_ADMIN_TOKEN=password
            - BGMI_HARDLINK_USE=true
            - FILEBROWSER_USE=true
            - TR_USER=bgmi
            - TR_PASS=password
            - TR_PEERPORT=51413
        image: 'ddsderek/bgmi-all-in-one:transmission'