#!/usr/bin/with-contenv bash
# shellcheck shell=bash

. /home/bgmi-docker/init_base

cat /home/bgmi-docker/utils/BGmi-Docker.logo
echo "Current crontab is:"
crontab -l

echo "Software version information:"
versions_dir="/versions"
for file in "$versions_dir"/*; do
    if [ -f "$file" ]; then
        filename=$(basename "$file" .txt)
        content=$(cat "$file")
        echo "$filename $content"
    fi
done