#!/usr/bin/with-contenv bash

function 010_config {
umask "${UMASK}"

echo -e "PUID=${PUID}
PGID=${PGID}
Umask=${UMASK}"

groupmod -o -g "$PGID" nt
usermod -o -u "$PUID" nt

media_cartoon=${MEDIA_DIR}
meida_downloads=${DOWNLOAD_DIR}
if [ ! -d $media_cartoon ]; then
	mkdir -p $media_cartoon
fi
if [ ! -d $meida_downloads ]; then
	mkdir -p $meida_downloads
fi
if [ ! -d /config ]; then
	mkdir /config
fi
chown -R nt:nt "${NT_HOME}" /config /etc/hosts
if [[ "$(stat -c '%U' /media)" != "nt" ]] || [[ "$(stat -c '%G' /media)" != "nt" ]]; then
    chown nt:nt \
        /media
fi
if [[ "$(stat -c '%U' ${MEDIA_DIR})" != "nt" ]] || [[ "$(stat -c '%G' ${MEDIA_DIR})" != "nt" ]]; then
    chown nt:nt \
        ${MEDIA_DIR}
fi
if [[ "$(stat -c '%U' ${DOWNLOAD_DIR})" != "nt" ]] || [[ "$(stat -c '%G' ${DOWNLOAD_DIR})" != "nt" ]]; then
    chown nt:nt \
        ${DOWNLOAD_DIR}
fi
}

010_config 2>&1 | sed "s#^#cont-init: info: $(realpath $0): \1#g"