version: '3.3'
services:
    bgmi-all-in-one:
        container_name: bgmi
        restart: always
        volumes:
            - '/root/config/bgmi:/bgmi'
            - '/media:/media'
        ports:
            - '80:80'
        environment:
            - TZ=Asia/Shanghai
            - PGID=1000
            - PUID=1000
            - UMASK=022
            - MEDIA_DIR=/media/cartoon
            - DOWNLOAD_DIR=/media/downloads
            - BGMI_DATA_SOURCE=mikan_project
            - BGMI_HTTP_ADMIN_TOKEN=password
        image: 'ddsderek/bgmi-all-in-one:latest'