version: '3.3'
services:
    bgmi:
        image: ddsderek/bgmi-all-in-one:latest
        container_name: "bgmi"
        restart: "always"
        volumes:
          - /bgmi:/bgmi
          - /media:/media
        ports:
            - '80:80'
        environment:
          - TZ=Asia/Shanghai
          - PGID=1000
          - PUID=1000
          - UMASK=022
          - MEDIA_DIR=/media/cartoon
          - DOWNLOAD_DIR=/media/downloads
          - BGMI_DOWNLOADER=false
          - BGMI_SOURCE=mikan_project
          - BGMI_ADMIN_TOKEN=password