#!/usr/bin/with-contenv bash
# shellcheck shell=bash

. /home/bgmi-docker/init_base

nginx_run="/var/run/nginx"
bgmi_conf="/bgmi/conf/bgmi"
bgmi_nginx="/bgmi/conf/nginx"
filebrowser_conf="/bgmi/conf/filebrowser"
media_cartoon=${MEDIA_DIR}
meida_downloads=${DOWNLOAD_DIR}

if [ ! -f "${first_lock}" ]; then

	if [ ! -d ${nginx_run} ]; then
		mkdir -p ${nginx_run}
	fi

	if [ ! -d ${bgmi_conf} ]; then
		mkdir -p ${bgmi_conf}
	fi

	if [ ! -d ${bgmi_nginx} ]; then
		mkdir -p ${bgmi_nginx}
	fi

	if [ "${FILEBROWSER_USE}" == "true" ]; then
		if [ ! -d ${filebrowser_conf} ]; then
			mkdir -p ${filebrowser_conf}
		fi
	fi

	if [ ! -d ${media_cartoon} ]; then
		mkdir -p ${media_cartoon}
	fi

	if [ ! -d ${meida_downloads} ]; then
		mkdir -p ${meida_downloads}
	fi

fi