#!/bin/bash
#     _         _       ____    ____
#    / \   _ __(_) __ _|___ \  |  _ \ _ __ ___
#   / _ \ | '__| |/ _` | __) | | |_) | '__/ _ \
#  / ___ \| |  | | (_| |/ __/  |  __/| | | (_) |
# /_/   \_\_|  |_|\__,_|_____| |_|   |_|  \___/
#
# https://github.com/P3TERX/Aria2-Pro-Docker https://github.com/DDS-Derek/Aria2-Pro-Docker
#
# Copyright (c) 2020-2022 P3TERX <https://p3terx.com> DDSRem DDSDerek <https://blog.ddsrem.gq>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.

. /home/bgmi-docker/dl_tools/aria2/aria2_pro/etc/init-base

INSTALL_RCLONE() {
    if [[ ! -f /usr/local/bin/rclone ]]; then
        echo
        echo -e "${INFO} Installing RCLONE ..."
        [[ -L /usr/bin/unzip ]] && rm -f /usr/bin/unzip
        curl -fsSL https://rclone.org/install.sh | bash
    fi
}

if [[ "${SPECIAL_MODE}" = "rclone" ]]; then
    INSTALL_RCLONE
    PROFILES="upload.sh rclone.env"
elif [[ "${SPECIAL_MODE}" = "move" ]]; then
    PROFILES="move.sh"
else
    PROFILES="clean.sh"
fi

DOWNLOAD_PROFILE

exit 0
