version: '3.3'
services:
    bgmi-docker-all-in-one:
        container_name: bgmi
        restart: always
        volumes:
            - '/bgmi:/bgmi'
            - '/home/video2/NEW:/media'
        ports:
            - '80:80'
            - '6800:6800'
            - '6880:6880'
            - '6888:6888/tcp'
            - '6888:6888/udp'
        environment:
            - TZ=Asia/Shanghai
            - PGID=1000
            - PUID=1000
            - UMASK=022
            - DOWNLOADER=aria2
            - BGMI_SOURCE=mikan_project
            - BGMI_ADMIN_TOKEN=password
            - UPDATE_TRACKERS=true
            - CUSTOM_TRACKER_URL=
            - LISTEN_PORT=6888
            - RPC_PORT=6800
            - RPC_SECRET=
            - DISK_CACHE=
            - IPV6_MODE=
            - SPECIAL_MODE=
        image: 'ddsderek/bgmi-docker-all-in-one:latest'