#!/usr/bin/with-contenv bash
# shellcheck shell=bash

umask ${UMASK}

exec \
    s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost 8098" \
    s6-setuidgid bgmi filebrowser -c /bgmi/conf/filebrowser/settings.json -d /bgmi/conf/filebrowser/filebrowser.db --noauth