repos:
  - repo: https://github.com/Trim21/pre-commit-hooks
    rev: 2cd566d7d05582364aaa111f4522efd33857346c  # frozen: v0.5.1
    hooks:
      - id: poetry-check-lock
      - id: find-trailing-comma

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: db7346d375eda68a0174f2c057dd97f2fbffe030  # frozen: v4.2.0
    hooks:
      - id: check-merge-conflict
        exclude: \.rst$

      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first

      - id: mixed-line-ending
        args: [--fix=lf]
        exclude: \.vbs$

      - id: mixed-line-ending
        args: [--fix=crlf]
        files: \.vbs$

      - id: check-json
      - id: check-added-large-files # check for file bigger than 500kb
      - id: check-yaml
      - id: debug-statements
      - id: fix-encoding-pragma
        args: [--remove]

  - repo: https://github.com/asottile/pyupgrade
    rev: 4d35c00c9ff5a51a853a89137db5fdd2bdf0ca95  # frozen: v2.32.1
    hooks:
      - id: pyupgrade
        args: [--py37-plus]

  - repo: https://github.com/myint/autoflake
    rev: 7a53fdafc82c33f446915b60fcac947c51279260 # frozen: v1.4
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-unused-variables
          - --remove-all-unused-imports
          - --expand-star-imports

  - repo: https://github.com/timothycrosley/isort
    rev: c5e8fa75dda5f764d20f66a215d71c21cfa198e1  # frozen: 5.10.1
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: ae2c0758c9e61a385df9700dc9c231bf54887041  # frozen: 22.3.0
    hooks:
      - id: black
