name: 构建bgmi-docker-all-in-one镜像-tag
on:
  workflow_dispatch:
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@master
      
      - 
        name: Set Up QEMU
        uses: docker/setup-qemu-action@v2

      - 
        name: Set Up Buildx
        uses: docker/setup-buildx-action@v2
        
      - 
        name: Login DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - 
        name: Buildx
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          platforms: |
            linux/amd64
            linux/arm64/v8
            linux/arm/v7
            linux/arm/v6
          push: true
          tags: |
            ddsderek/bgmi-docker-all-in-one:${{ secrets.VERSION }}

      - 
        name: Buildx-notransmission
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile-notransmission
          platforms: |
            linux/amd64
            linux/arm64/v8
            linux/arm/v7
            linux/arm/v6
          push: true
          tags: |
            ddsderek/bgmi-docker-all-in-one:${{ secrets.VERSION }}-notransmission