name: Build BGmi-All-In-One image

on:
    release:
        types: [published]

jobs:
  bgmi:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@master
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/bgmi-all-in-one

      - 
        name: Set Up QEMU
        uses: docker/setup-qemu-action@v2

      - 
        name: Set Up Buildx
        uses: docker/setup-buildx-action@v2
        
      - 
        name: Login DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - 
        name: Build
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          platforms: |
            linux/386
            linux/amd64
            linux/arm64/v8
            linux/arm/v7
            linux/arm/v6
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/bgmi-all-in-one:${{ steps.meta.outputs.version }}
            ${{ secrets.DOCKER_USERNAME }}/bgmi-all-in-one:latest
          labels: ${{ steps.meta.outputs.labels }}

  transmission:
    needs: [bgmi]
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@master
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/bgmi-all-in-one

      - 
        name: Set Up QEMU
        uses: docker/setup-qemu-action@v2

      - 
        name: Set Up Buildx
        uses: docker/setup-buildx-action@v2
        
      - 
        name: Login DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - 
        name: Build
        uses: docker/build-push-action@v4
        with:
          context: .
          file: transmission.Dockerfile
          platforms: |
            linux/386
            linux/amd64
            linux/arm64/v8
            linux/arm/v7
            linux/arm/v6
          push: true
          build-args: |
            BGMI_TAG=${{ steps.meta.outputs.version }}
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/bgmi-all-in-one:${{ steps.meta.outputs.version }}-transmission
            ${{ secrets.DOCKER_USERNAME }}/bgmi-all-in-one:transmission
          labels: ${{ steps.meta.outputs.labels }}

  aria2:
    needs: [bgmi]
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@master
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/bgmi-all-in-one

      - 
        name: Set Up QEMU
        uses: docker/setup-qemu-action@v2

      - 
        name: Set Up Buildx
        uses: docker/setup-buildx-action@v2
        
      - 
        name: Login DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - 
        name: Build
        uses: docker/build-push-action@v4
        with:
          context: .
          file: aria2.Dockerfile
          platforms: |
            linux/386
            linux/amd64
            linux/arm64/v8
            linux/arm/v7
            linux/arm/v6
          push: true
          build-args: |
            BGMI_TAG=${{ steps.meta.outputs.version }}
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/bgmi-all-in-one:${{ steps.meta.outputs.version }}-aria2
            ${{ secrets.DOCKER_USERNAME }}/bgmi-all-in-one:aria2
          labels: ${{ steps.meta.outputs.labels }}

  nt:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@master
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/bgmi-all-in-one

      - 
        name: Set Up QEMU
        uses: docker/setup-qemu-action@v2

      - 
        name: Set Up Buildx
        uses: docker/setup-buildx-action@v2
        
      - 
        name: Login DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - 
        name: Build
        uses: docker/build-push-action@v4
        with:
          context: .
          file: NAStool.Dockerfile
          platforms: |
            linux/amd64
            linux/arm64/v8
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/bgmi-all-in-one:${{ steps.meta.outputs.version }}-nastools
            ${{ secrets.DOCKER_USERNAME }}/bgmi-all-in-one:nastools
          labels: ${{ steps.meta.outputs.labels }}