name: Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    name: Release
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3

      - 
        name: Set Version
        id: set-version
        run: |
          RELEASE_VERSION=$(jq -r '.Release_Version' info.json)

          echo "RELEASE_VERSION=${RELEASE_VERSION}"

          echo "RELEASE_VERSION=${RELEASE_VERSION}" >> $GITHUB_OUTPUT

      -
        name: Generate Release
        uses: actions/create-release@latest
        with:
          tag_name: ${{ steps.set-version.outputs.RELEASE_VERSION }}
          name: ${{ steps.set-version.outputs.RELEASE_VERSION }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}